security:
    encoders:
        UES\FO\SIGBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_TACTIC:       ROLE_USER
        ROLE_STRATEGIC:    ROLE_TACTIC
        ROLE_OPERATIVE:    ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_STRATEGIC, ROLE_OPERATIVE]

    providers:
        user_db:
            entity:
                class: SIGBundle:Usuario
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous: true
            security: false

        main:
            pattern: ^/
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: index
            logout:
                path: logout
                target: login
            remember_me:
                key: %secret%
                lifetime: 604800
                path: ^/
                domain: ~
            security: true
            anonymous: ~

    access_control:
        - { path: ^/bundles, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recover, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_OPERATIVE }
        - { path: ^/estrategico, roles: ROLE_STRATEGIC }
        - { path: ^/tactico, roles: ROLE_TACTIC }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
